##########################     INPUT FILE OPTIONS     ########################## 

# Binary input files
input_file_ref: './data/test2_102mhz/output1'  
input_file_srv: './data/test2_102mhz/output2'

##########################     OUTPUT FILE OPTIONS    ##########################

range_doppler_map_ftype: 'zarr' # file type for output- 'zarr' or 'hdf5'
output_fname: 'XAMBG_1011' # output base filename
num_frames: 1200 # number of range-doppler map frames to compute

##########################    INPUT DATA PARAMETERS    #########################

input_sample_rate: 2400000      # input sample rate in Hz
input_center_freq: 102000000    # input center frequency in Hz
channel_freq: 101900000         # center frequency of the FM radio channel in Hz
channel_bandwidth: 200000       # channel bandwidth in Hz

#########################    PROCESSING PARAMETERS    ##########################

# Nominal value for the coherent processing interval (CPI) in seconds. The doppler 
# resolution is inversely proportional to this, i.e. a 2 second CPI corresponds
# to a Doppler resolution of 0.5Hz.
cpi_seconds_nominal: 2.0 
max_doppler_nominal: 256.0  # The maximum desired doppler shift in Hz. 
max_range_nominal: 200.0    # The maximum desired bistatic range in km.
overlap_cpi: True           # whether to overlap CPI windows. 




